
//
var/list/dyeable_part_to_name = list(
	"sash" = "Sash",
	"belt" = "Belt",
	"polo" = "Polo",
	"polo-stripes" = "Polo Stripes",
	"polo-sleeves" = "Polo Sleeves",
	"tshirt" = "T-Shirt",
	"tshirt-stripes" = "T-Shirt Stripes",
	"shortpants" = "Short Pants",
	"shortpants-trim" = "Short Pants Trim",
	"pants" = "Long Pants",
	"pants-tip" = "Long Pants Tip",
	"tartankilt" = "Tartan Kilt",
	"pleatedskirt" = "Pleated Skirt",
	"straightskirt" = "Straight Skirt",
	"drape" = "Drape",
	"trim" = "Trim",
	"top" = "Top",
	"top-sleeves-whole" = "Sleeves",
	"top-sleeves-tip" = "Sleeves Tip",
	"top-shoulders" = "Sleeves Trim",
	"top-trim" = "Trim",
	"pants" = "Pants",
	"pants-tip" = "Pants Tip",
	)
